/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: f861741ecf17810a5d383f194e52d840)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
	}
	interface Env {
		DB: D1Database;
		AUTH_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
