/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime` (hash: 993e995a2ba01b92a93d4800cd7ce84f)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server/index");
	}
	interface Env {
		DB: D1Database;
		AUTH_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
